# site settings
title: Lorenzana Web Design
subtitle:
email: lorenzanamarcus@gmail.com
description: Beautiful and responsive websites designed with passion and precision.
baseurl: "" # the subpath of your site, e.g. /blog
url: https://lorenzanadesigns.com # the base hostname & protocol for your site
author: 'Marcus Lorenzana'
author_image: "/assets/img/team/marcus.jpg"
city: San Antonio
state: TX
zip_code: 78232
country: United States of America
phone: 210-286-7939

permalink: "/blog/:categories/:year/:month/:day/:title.html"

# social settings
linkedin_url: https://www.linkedin.com/in/lorenzanamarcus/
thumbtack_url: https://www.thumbtack.com/biz/marcus-lorenzana

# build settings
markdown: kramdown

sass:
  style: compressed

plugins:
  - jekyll-seo-tag
